defmodule Soothsayer.MissingDataTest do
  use ExUnit.Case, async: true

  alias Explorer.DataFrame
  alias Soothsayer.MissingData

  doctest MissingData

  @missing %{impute: true, impute_linear: 10, impute_rolling: 10, drop_samples: false}

  describe "impute/3" do
    # Generated by test/fixtures/missing_data/pandas_fill_linear_then_rolling_avg.py
    # with pandas, running NeuralProphet's fill_linear_then_rolling_avg on
    # the same inputs.
    test "matches NeuralProphet's fill_linear_then_rolling_avg position by position" do
      cases =
        "test/fixtures/missing_data/pandas_fill_linear_then_rolling_avg.json"
        |> File.read!()
        |> JSON.decode!()

      assert length(cases) == 8

      for %{"name" => name, "input" => input, "linear" => linear, "rolling" => rolling} =
            reference <- cases do
        result = MissingData.impute(input, linear, rolling)
        expected = reference["output"]
        assert length(result) == length(expected), name

        for {{got, want}, index} <- Enum.zip(result, expected) |> Enum.with_index() do
          case {got, want} do
            {nil, nil} -> :ok
            {got, want} when is_float(got) and is_float(want) -> assert_in_delta got, want, 1.0e-9
            _ -> flunk("#{name} position #{index}: got #{inspect(got)}, want #{inspect(want)}")
          end
        end
      end
    end

    test "a gap within twice the linear limit is a straight line" do
      assert MissingData.impute([2.0, nil, nil, nil, 10.0], 2, 0) == [2.0, 4.0, 6.0, 8.0, 10.0]
    end

    test "a long gap keeps its middle open, all or nothing when rolling is short" do
      values = [1.0, 1.0] ++ List.duplicate(nil, 7) ++ [1.0, 1.0]

      # 2 * 2 + 3 = 7 fits, so everything is filled
      assert Enum.all?(MissingData.impute(values, 2, 3), &(&1 == 1.0))

      # one more missing value than the window covers leaves the middle open
      longer = [1.0, 1.0] ++ List.duplicate(nil, 8) ++ [1.0, 1.0]
      result = MissingData.impute(longer, 2, 3)
      assert Enum.count(result, &is_nil/1) == 4
      assert Enum.slice(result, 2, 2) == [1.0, 1.0]
      assert Enum.slice(result, 8, 2) == [1.0, 1.0]
    end

    test "nothing is filled without limits" do
      assert MissingData.impute([1.0, nil, 3.0], 0, 0) == [1.0, nil, 3.0]
    end
  end

  describe "prepare/3" do
    defp frame(dates, y, extra \\ %{}) do
      DataFrame.new(Map.merge(%{"ds" => dates, "y" => y}, extra))
    end

    defp config(overrides \\ %{}) do
      Soothsayer.new(overrides).config
    end

    test "without auto-regression drops the rows with a missing y and keeps gaps" do
      dates = [~D[2023-01-01], ~D[2023-01-02], ~D[2023-01-04], ~D[2023-01-05]]

      {prepared, remaining} =
        MissingData.prepare(frame(dates, [1.0, nil, :nan, 4.0]), config(), {1, :day})

      assert DataFrame.to_columns(prepared, atom_keys: false) == %{
               "ds" => [~D[2023-01-01], ~D[2023-01-05]],
               "y" => [1.0, 4.0]
             }

      assert remaining == %{"y" => MapSet.new()}
    end

    test "with auto-regression inserts the missing rows and imputes them" do
      dates = [~D[2023-01-01], ~D[2023-01-02], ~D[2023-01-04], ~D[2023-01-05]]
      config = config(%{ar: %{enabled: true, lags: 2}})

      {prepared, remaining} =
        MissingData.prepare(frame(dates, [1.0, 2.0, 4.0, 5.0]), config, {1, :day})

      assert DataFrame.to_columns(prepared, atom_keys: false) == %{
               "ds" => Enum.map(0..4, &Date.add(~D[2023-01-01], &1)),
               "y" => [1.0, 2.0, 3.0, 4.0, 5.0]
             }

      assert remaining == %{"y" => MapSet.new()}
    end

    test "with auto-regression drops trailing missing rows and reports what stays open" do
      dates = Enum.map(0..49, &Date.add(~D[2023-01-01], &1))
      y = [1.0, 2.0] ++ List.duplicate(nil, 40) ++ [43.0, 44.0, 45.0, 46.0, 47.0, 48.0, nil, nil]
      config = config(%{ar: %{enabled: true, lags: 2}})
      {prepared, remaining} = MissingData.prepare(frame(dates, y), config, {1, :day})

      assert DataFrame.n_rows(prepared) == 48
      # 10 filled linearly from each side of the 40 long gap, 20 stay open
      assert MapSet.size(remaining["y"]) == 20
      assert Enum.min(remaining["y"]) == 12 and Enum.max(remaining["y"]) == 31
      assert prepared["y"][11] != :nan and prepared["y"][12] == :nan
    end

    test "with auto-regression an off-grid timestamp raises" do
      dates = [~D[2023-01-01], ~D[2023-01-02], ~D[2023-01-04], ~D[2023-01-05]]
      config = config(%{ar: %{enabled: true, lags: 2}})

      assert_raise ArgumentError, ~r/2023-01-02 is not on the 2 day grid/, fn ->
        MissingData.prepare(frame(dates, [1.0, 2.0, 4.0, 5.0]), config, {2, :day})
      end
    end

    test "regressor columns are imputed with or without auto-regression" do
      dates = Enum.map(0..4, &Date.add(~D[2023-01-01], &1))

      data =
        frame(dates, [1.0, 2.0, 3.0, 4.0, 5.0], %{"temperature" => [10.0, nil, nil, 13.0, 14.0]})

      config = config(%{regressors: ["temperature"]})
      {prepared, remaining} = MissingData.prepare(data, config, {1, :day})

      assert Explorer.Series.to_list(prepared["temperature"]) == [10.0, 11.0, 12.0, 13.0, 14.0]
      assert remaining["temperature"] == MapSet.new()
    end

    test "without auto-regression an unfilled regressor drops the row or raises" do
      dates = Enum.map(0..4, &Date.add(~D[2023-01-01], &1))

      data =
        frame(dates, [1.0, 2.0, 3.0, 4.0, 5.0], %{"temperature" => [10.0, nil, 12.0, 13.0, 14.0]})

      strict = config(%{regressors: ["temperature"], missing: %{impute: false}})

      assert_raise ArgumentError, ~r/1 training samples touch missing values/, fn ->
        MissingData.prepare(data, strict, {1, :day})
      end

      lenient =
        config(%{regressors: ["temperature"], missing: %{impute: false, drop_samples: true}})

      {prepared, _remaining} = MissingData.prepare(data, lenient, {1, :day})
      assert DataFrame.n_rows(prepared) == 4
    end

    test "y without a single value raises" do
      assert_raise ArgumentError, ~r/y column has no values/, fn ->
        MissingData.prepare(
          frame([~D[2023-01-01], ~D[2023-01-02]], [nil, :nan]),
          config(),
          {1, :day}
        )
      end
    end
  end

  describe "fill_history/4" do
    test "regrids and imputes, leaving what it can't fill as nil" do
      timestamps = [~N[2023-01-01 00:00:00], ~N[2023-01-01 02:00:00], ~N[2023-01-01 03:00:00]]

      assert MissingData.fill_history(timestamps, [1.0, :nan, 4.0], {1, :hour}, @missing) ==
               {Enum.map(0..3, &NaiveDateTime.add(~N[2023-01-01 00:00:00], &1, :hour)),
                [1.0, 2.0, 3.0, 4.0]}

      assert MissingData.fill_history([], [], {1, :hour}, @missing) == {[], []}
    end
  end
end
